package com.example.mensai.domain

enum class Foods {
    UNKNOWN,
    PASTATELLER,
    ALASKA_SEELACHS_EIHUELLE,
    SCHWARZBIERPFANNE,
    SEELACHS_PANADE,
    ELSAESSER_HAENCHEN,
    MANGO_SPARGEL_PFANNE,
    ALASKA_SEELACHS_HOLLANDAISE,
    FLADENBROT_KEBAP,
    FRUEHLINGSROLLE,
    PUTENGYROS,
}